name: result_handler
description: A simple and powerful library for handling results (successes and failures) in Dart, inspired by Either from functional programming libraries like dartz.
version: 1.2.2
repository: https://github.com/Mahmoud-Saeed-Mahmoud/result_handler
homepage: https://mahmoud-saeed-mahmoud.github.io/result_handler/

environment:
  sdk: ">=3.0.0 <=4.0.0"

dev_dependencies:
  lints: ^5.0.0
