name: result_handler
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Mahmoud-Saeed-Mahmoud/result_handler
homepage: https://mahmoud-saeed-mahmoud.github.io/result_handler/

environment:
  sdk: ^3.6.0


dev_dependencies:
  lints: ^5.0.0
